<div class="slider-admin-tools"><h2><?php echo utf8_htmlentities($slider['title']) ?> <span class="slider-count"><?php echo count($slides) ?></span></h2><?php echo $this->button((string)$this->lang('Back'))->icon('fas fa-arrow-left')->color('secondary')->url('admin/slider') ?><?php echo $this->button('Apercu')->icon('far fa-eye')->color('secondary')->url('admin/slider/preview/'.$slider['slider_id']) ?><?php echo $this->button_update('admin/slider/edit/'.$slider['slider_id']) ?><?php echo $this->button_create('admin/slider/slides/add/'.$slider['slider_id'], (string)$this->lang('Add slide')) ?></div>
<div class="slider-order-status" role="status" aria-live="polite"></div>
<ul class="slider-slide-list" data-slider-sort="<?php echo url('admin/slider/sort/'.$slider['slider_id']) ?>" data-token="<?php echo utf8_htmlentities($sort_token) ?>">
<?php foreach ($slides as $index => $row): ?><li class="slider-slide-row" data-id="<?php echo (int)$row['slide_id'] ?>">
<div class="slider-reorder"><?php echo str_replace('hb-sortable', 'slider-drag', (string)$this->button_sort($row['slide_id'], 'admin/slider/sort/'.$slider['slider_id'], '.slider-slide-list', '> li.slider-slide-row')) ?></div>
<a class="slider-slide-preview" href="<?php echo url('admin/slider/slides/edit/'.$row['slide_id']) ?>"><?php if ($row['image_path']): ?><img src="<?php echo utf8_htmlentities(url($row['image_path'])) ?>" alt="" loading="lazy" /><?php else: ?><?php echo icon('far fa-image') ?><?php endif ?></a>
<div class="slider-slide-info"><h3><a href="<?php echo url('admin/slider/slides/edit/'.$row['slide_id']) ?>"><?php echo utf8_htmlentities($row['title'] ?: 'Slide '.$row['slide_id']) ?></a></h3><p><?php echo utf8_htmlentities($row['description']) ?></p><?php if ($row['button_label']): ?><span class="slider-button-summary"><?php echo icon('fas fa-link') ?> <?php echo utf8_htmlentities($row['button_label']) ?></span><?php endif ?><?php if (!$row['image_path']): ?><span class="slider-missing">Image supprimee</span><?php endif ?></div>
<span class="ui tiny <?php echo $row['published'] ? 'green' : '' ?> label"><?php echo $row['published'] ? 'Active' : 'Inactive' ?></span>
<div class="slider-admin-actions"><?php echo $this->button_update('admin/slider/slides/edit/'.$row['slide_id']) ?><?php echo $this->button_delete('admin/slider/slides/delete/'.$row['slide_id']) ?></div>
</li><?php endforeach ?></ul>
<?php if (!$slides): ?><div class="slider-empty"><?php echo icon('far fa-images') ?><p><?php echo $this->lang('No slides') ?></p></div><?php endif ?>
